services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
    
  api:
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "9999:9999"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DB=openhands_telemetry
      - ENVIRONMENT=production
    restart: always
    
  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard.Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:9999
    restart: always

volumes:
  mongo_data: